- name: create wallpaper directory
  file:
    path: ~/.config/wallpapers
    state: directory
  tags:
    - wallpapers

- name: symlink dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/wallpapers/files/{{ item }}"
    path: ~/.config/wallpapers/{{ item }}
    state: link
    follow: false
    force: yes
  loop:
    - AssemblyBackground.png
    - crimson.png
    - solid-background.png
  tags:
    - wallpapers
