- name: create i3 config directory
  file:
    path: ~/.config/i3
    state: directory
  tags:
    - i3

- name: symlink dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/i3/files/{{ item }}"
    path: ~/.config/i3/{{ item }}
    state: link
    follow: false
    force: yes
  loop:
    - config
  tags:
    - i3
