- name: install utils
  become: yes
  apt:
    name:
      - feh
      - flameshot
      - bat
      - ncdu
      - xclip
      - tree
      - alsa-utils
      - thunar
      - neofetch
      - pavucontrol
  tags:
    - apt

- name: install exa
  shell: cargo install exa
  tags:
    - exa

- name: install fd-find
  shell: cargo install fd-find
  tags:
    - cargo

- name: install ripgrep
  shell: cargo install ripgrep
  tags:
    - cargo

- name: install procs
  shell: cargo install procs
  tags:
    - cargo

      #- name: install onefetch
      #  shell: cargo install onefetch
      #  tags:
      #    - cargo

- name: install vimv
  become: yes
  shell: |
    curl https://raw.githubusercontent.com/thameera/vimv/master/vimv > /usr/bin/vimv
    chmod +755 /usr/bin/vimv
