- name: install docker
  become: yes
  apt:
    name:
      - docker.io
      - docker-compose
  tags:
    - apt
    - docker

- name: add user to docker group
  become: yes
  # verify this works
  command:  "gpasswd -a {{ ansible_env.USER }} docker"
  tags:
    - docker

- name: reload docker group
  become: yes
  command: newgrp docker
  tags:
    - docker
