[icons]
name = "awesome"

[theme.overrides]
idle_bg = "#1B512D"
idle_fg = "#fffffff"
info_bg = "#1B512D"
info_fg = "#fafafa"
good_bg = "#1C7C54"
good_fg = "#fffffff"
warning_bg = "#5B9279"
warning_fg = "#ffffff"
critical_bg = "#DEF4C6"
critical_fg = "#1C7C54"
separator = "<span font='15'>î‚²</span>"
separator_bg = "auto"
separator_fg = "auto"

[[block]]
block = "focused_window"
max_width = 75
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
dynamic_width = true
hide_when_empty = true
max_width = 30

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %m/%d %I:%M %p"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "custom"
command = "whoami"
interval = "once"

[[block]]
block = "custom"
command = "cat /etc/hostname"
interval = "once"

[[block]]
block = "custom"
command = "mullvad status | awk -F ' ' '{print $1}'"
interval = 5
