- name: install jetbrains mono font
  become: yes
  apt:
    name:
      - fonts-jetbrains-mono
  tags:
    - fonts
    - jetbrains mono

- name: install fira code font
  become: yes
  apt:
    name:
      - fonts-firacode
  tags:
    - fonts
    - fira code

- name: install powerline fonts
  become: yes
  apt:
    name:
      - fonts-powerline
  tags:
    - fonts
    - powerline

- name: install monocraft
  shell: |
    fc-list | grep Monocraft || curl -L -O https://github.com/IdreesInc/Monocraft/releases/download/v1.1/Monocraft.otf \
      mkdir ~/.local/share/fonts \
      mv Monocraft.otf ~/.local/share/fonts \
      fc-cache -f -v

